### ISSUE TITLE
下载文件音画不同步

### ISSUE THREAD

**Issue by MilarvozM** [Last-Order/Minyami#100]
**Basic Information**
* Node.js version: 14.17.5
* Minyami version: 4.7.1
* Video URL: 因为是直播所以直播链已失效
* 录播地址：https://hls-auth.cloud.stream.co.jp/mediaplaylist/smNmn2UDno5gG4T4TYx2cocR/transcoded/p3rtwzo6mvyvuel8_ewnqxg1o7mjxdvz6_ZuwkXDPRerBBeYq7BBP9Dg_1_20220424-22-55-40_0_1080p.m3u8

**Describe the bug**
直播流下载后音频Delay relative to video        : -20 ms
视频archive版则是-36ms

**Comment by fireattack** [comment]
我不知道你保存的是什么格式，但是一般而论视频有名义上的delay relative to video（尤其是如果2次封装过）是非常正常的，纯粹是因为A/V的Frame rate不能整除为了对齐而已。和minyami没有什么关系也不会因此导致额外的音画不同步

**Comment by Last-Order** [comment]
火哥哥说得对，这个问题和mnm没有关系，请自行排查
