### ISSUE TITLE
nico录播下载一段时间后无限403报错

### ISSUE THREAD

**Issue by aszz** [Last-Order/Minyami#102]
**Basic Information**
* Node.js version: v16.14.0
* Minyami version: 4.7.2
* Minyami Extractor (Chrome Extension) version:1.4.3
* Video URL: https://live.nicovideo.jp/watch/lv336848164?ref=pc_mypage_nicorepo

我总觉得是我下载速度太快导致被banIP了。。。
但是我已经把并发数设成1了。。目前在日本也换不了ip，实在没什么办法再降速了
有什么好解决办法嘛
![QQ截图20220513002502](https://user-images.githubusercontent.com/101473410/168111297-33a75ac0-3992-4904-93cc-61874f363957.png)

**Comment by fireattack** [comment]
别的地方又开了一个session把你自己下载的挤掉了吧

**Comment by aszz** [comment]
一直是白金会员，然后最高画质。
我现在在日本，不是用的梯子，应该网络是没问题的。。估计是我家网的ip不太行？

**Comment by Last-Order** [comment]
不如试试16线程 还不行就可能你IP真被ban了

**Comment by aszz** [comment]
刚刚用手机热点试了下，虽然很慢但是无事下完了.....
估计真的是ip被ban了....明明都是softbank的网：(
说起来用热点下的时候会像以前一样开始下载后播放页面会自动刷新一次，用网线下的话就不会...很怪

**Comment by Last-Order** [comment]
倒也不是很怪，这个表现就是因为Minyami无法和Nico建立Websocket连接（如果建立成功了，刷新Token时候播放器的session会被顶掉，表现为刷新）
