### ISSUE TITLE
nico时光机无法下载

### ISSUE THREAD

**Issue by nutari** [Last-Order/Minyami#107]
RT，挂了代理之后可以抓到M3U8，但是所有的chunk都是404 not found
![QQ图片20220906224721](https://user-images.githubusercontent.com/3312586/188651735-a456b55a-9046-4910-8acc-77df3e662a88.png)

**Comment by Last-Order** [comment]
请提供视频链接、版本号等基本信息。

**Comment by nutari** [comment]
视频链接 https://live.nicovideo.jp/watch/lv338322952?ref=notify&zroute=subscribe
插件给的命令 minyami -d "https://vodedge750.dmc.nico/hlsarchive/ht2_nicolive/nicolive-production-pg29500055224942_f39c69e4b48c4e246bb71fd913e3160ba7c377d979c7a5b4650f4710a136ed88/2/ts/playlist.m3u8?start_time=-575289790209&ht2_nicolive=8632497.chxm95t8hj_rhsjft_uf1cvcjrrka3&start=1217.856" --output "好きなことして生きていく！#86 - 2022_9_6(火) 20_55開始 - ニコニコ生放送.ts" --key "29500055224942_8632497_1662558181_85b0d755e41c9089e6b8b3a9f15217033f050de6,super_high"
minyami版本 4.8.0

**Comment by Last-Order** [comment]
![image](https://user-images.githubusercontent.com/3362825/188687707-0407078a-cf64-4682-a1c4-09bf514b6ed0.png)
你好，是否进行过此操作

**Comment by nutari** [comment]
> ![image](https://user-images.githubusercontent.com/3362825/188687707-0407078a-cf64-4682-a1c4-09bf514b6ed0.png) 你好，是否进行过此操作

可以用了，感谢。
