### ISSUE TITLE
A special case of AbemaTV

### ISSUE THREAD

**Issue by doe1080** [Last-Order/Minyami#108]
**Basic Information**
* Node.js version: v18.4.0
* Minyami version: 4.8.0
* Minyami Extractor (Chrome Extension) version: 1.4.7
* Video URL: https://abema.tv/channels/abema-anime-3/slots/D1mDS1GN18rSMV

This video URL for AbemaTV is in the format "https://abema.tv/channels/*/slots/*" which is currently supported.
However unlike the others, this video could not be downloaded.
One feature that makes this video different from others is that MPD is detected by the .MPD Detector.

On the other hand, yt-dlp was able to download it from HLS.
As we can confirm that m3u8 is also present from "https://api.abema.io/v1/media/slots/D1mDS1GN18rSMV", perhaps only some of them are special and the rest can be processed in the same way as in the general case.
m3u8: "https://vod-abematv.akamaized.net/slot/D1mDS1GN18rSMV/1080/playlist.m3u8?aver=EBnVqVY4RTNsbV"

So could you please consider handling this case as well?

***
This video [NBCUniversal Anime×Music 30周年 24時間テレビ ②](https://abema.tv/channels/abema-anime-3/slots/D1mDS1GN18rSMV) will be expired in 3 days.
Sorry for the delay in reporting.

**Comment by Last-Order** [comment]
Hello deo1080. Thanks for your reporting.
In short, Minyami can't support this kind of videos and I recommend using streamlink to download it.

Minyami-chrome-extension is using a special method which is much more simplified than streamlink to get encrypt keys for abema. It relies on some JavaScript mechanisms than abema's HLS player is using and doesn't work on DASH players. Although I can implement the same method that streamlink is using in Minyami but it's a little bit too heavy for a single site.
