### ISSUE TITLE
[MINYAMI][WARN] Downloading or decrypting video-636e6570dfae500000.ts failed. Retry later. [Key [] length [0] or form invalid.]

### ISSUE THREAD

**Issue by ebatgmx** [Last-Order/Minyami#109]
**Basic Information**
* Node.js version: v19.1.0
* Minyami version: 4.8.0
* Minyami Extractor (Chrome Extension) version: 1.4.7
* Video URL: https://storage.ulama.io/lesson/42491/video-636e6570dfae5.m3u8

**Describe the bug**
Minyami is in loop over these errors:
`[MINYAMI][WARN] Downloading or decrypting video-636e6570dfae500000.ts failed. Retry later. [Key [] length [0] or form invalid.]`

**To Reproduce**
`minyami -d https://storage.ulama.io/lesson/42491/video-636e6570dfae5.m3u8 --cookies cookies.txt`

**Expected behavior**
I expected the video will be downloaded.

**Screenshots**
below the beginning of the m3u8 file:
`#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:13
#EXT-X-KEY:METHOD=AES-128,URI="https://hrdonline.ulama.io/webhook/datakey/4a85893ded100b9f592f36a9e9473a7c",IV=0x772610602c9efe1808545f135c3b86a5
#EXTINF:12.066667,
video-636e6570dfae500000.ts
#EXTINF:9.000000,
video-636e6570dfae500001.ts
#EXTINF:9.000000,
video-636e6570dfae500002.ts
#EXTINF:12.000000,
video-636e6570dfae500003.ts
#EXTINF:9.000000,
video-636e6570dfae500004.ts
#EXTINF:9.000000,
video-636e6570dfae500005.ts`

I've attached the cookies's file downloaded from browser.
[cookies.txt](https://github.com/Last-Order/Minyami/files/10034210/cookies.txt)

**Comment by Last-Order** [comment]
It seems that the key needs other authentication info to access such as Referer, User-Agent, etc. Please first try to provide these headers to Minyami.
If it doesn't help, could you please email your account & password and the link to the video to me (via the mail on my profile) so I can further inspect the issue. Thanks.

**Comment by fireattack** [comment]
Fixed with 

```bash
minyami -d https://storage.ulama.io/lesson/42491/video-636e6570dfae5.m3u8 --cookies cookies.txt --headers "referer:ulama.io"
```

**Comment by ebatgmx** [comment]
It worked for me. Thank you.
