### ISSUE TITLE
轉檔影片時間出現錯誤，無法正確索引

### ISSUE THREAD

**Issue by Nekofoxmiu** [Last-Order/Minyami#110]
**Basic Information**
* Node.js version: 18.9.0
* Minyami version: 4.8.2
* Minyami Extractor (Chrome Extension) version: 1.4.7 總之是最新現在掛上去的那個
* Video URL: https://abema.app/jsXc 要日區VPN

**Describe the bug**
合併後檔案變為多段ts檔裝至一個容器，
導致時間軸出現錯誤，七個小時的影片會只剩下兩個小時，並無法正確索引，透過ffmpeg重新封裝可解決

**To Reproduce**
複製插件指令貼至命令列
下載完成後錯誤出現
通過 ffmpeg -i "原檔案" -c copy 後檔案.ts 指令可修復，並且ffmpeg會提示有 Non-monotonous DTS 的問題產生

**Expected behavior**
正確的時間，可跳轉的時間軸

**Screenshots**
![image](https://user-images.githubusercontent.com/76677660/210162191-f54c30e7-d46b-4bc8-8fca-6f6feb6d3d2d.png)
![image](https://user-images.githubusercontent.com/76677660/210162237-1fe8472d-c466-4daa-a0d8-1434ee557a2d.png)

**Comment by fireattack** [comment]
是回放么，abema的回放如果他剪辑过（去广告etc.）是这样的，自己remux一次格式就是了 不是下载器的问题

**Comment by Nekofoxmiu** [comment]
行 回放沒錯
