### ISSUE TITLE
下载dmm在线直播时一直不断下载重覆文件~

### ISSUE THREAD

**Issue by MOMOKA88** [Last-Order/Minyami#115]
最近下载DMM的在线直播时不知道为何一直不断重覆下载相同档案,
导致整个视频不断画面重覆

如下图暂存档绿框就是重覆的档案
[https://imgur.com/Dhy83S4](url)

**Comment by Last-Order** [comment]
可以提供一下样例的m3u8吗

**Comment by MOMOKA88** [comment]
> 可以提供一下样例的m3u8吗


这个吗?
https://awsakbpri.dmm.com/livestreaming/akb48/amlst:akb48_fixhd:OHIef0nc3bD3nR6wTW75QTjdfvFKDyt77Uin%2BtvYD0zubc%2BLuFuqX3J72BCk4Cp-NfpQyLj6hMrh33ZQ0uwpMJv6RDvRFJM3nL8zVUSUGzLKBlpcyon3VE0fb0RkDe1shAZ83FM5pM8Di%2B6OS7jfJV3REcsoMMZcjJmJxZVcpLc%3D/chunklist_b6000000.m3u8?tc=49517680

**Comment by Last-Order** [comment]
初步看了下应该是DMM最近改了下，今天迟一点我兼容一下。

**Comment by MOMOKA88** [comment]
> 初步看了下应该是DMM最近改了下，今天迟一点我兼容一下。

好的,谢谢

**Comment by Last-Order** [comment]
请试一下最新的 5.0.2 版本。
