### ISSUE TITLE
下载nicolive会限live视频，每次30分钟左右就容易中断

### ISSUE THREAD

**Issue by aawwsslll** [Last-Order/Minyami#117]
软件版本5.02，插件版本 1.48。
下载链接：https://live.nicovideo.jp/watch/lv341820915

偶尔报上面的403错误，没开nico的白金会员。难道是下载nico的会员live视频一定要给cookies吗，
注意到下载失败的时候，浏览器插件又获取到新的视频链接。前面只有一个链接虽然偶尔报403但是下载正常。
另外注意到下载过程中ts会分成好几个文件，不知道这是否正常。

<img width="692" alt="image" src="https://github.com/Last-Order/Minyami/assets/16276853/b846758b-010e-4e9e-aa5a-c64d87f87172">

**Comment by fireattack** [comment]
报一定数量的403是正常的，不影响下载。
如果会导致断掉下不完一般是同一个账号同一个LV开太多session。

**Comment by aawwsslll** [comment]
重新测试了一遍还是一样，30分钟后插件自动获取了另外两条链接（浏览器播放窗口我是暂停的），然后就又下载失败了

**Comment by Last-Order** [comment]
Nico直播并未完整支持，建议直接下载回放（Timeshift）

**Comment by aawwsslll** [comment]
> Nico直播并未完整支持，建议直接下载回放（Timeshift）

我找到了https://github.com/guest-nico/nicoNewStreamRecorderKakkoKari， 这个软件看看能不能录制成功。
