### ISSUE TITLE
Twitcasting直播录制不断重复失败的块，也不会跳过

### ISSUE THREAD

**Issue by Hirumas** [Last-Order/Minyami#118]
直播不断重复尝试失败的块
设置了retries 5也是不顶用。。。
就卡在那里不动了。。。

**Comment by Hirumas** [comment]
或者有没有记录哪些块是哪个cmd开启的。。
不然好几个直播一起开分不清哪些块是哪个主播的。

**Comment by Last-Order** [comment]
请提供版本号等基础信息

**Comment by Hirumas** [comment]
版本号为5.0.2
https://img.chkaja.com/80c41be56108109e.png
命令是直接复制google插件然后加了--live  --reties 5
出现这种情况是已经主播已经停止放送，亦或者就是直接断了接不回去。

**Comment by Last-Order** [comment]
按照目前逻辑这种情况会在每个块重试次数达到设定的次数（5次）之后被丢弃，输出文件分段。目前从你的Log里无法判断是否已经达到重试次数。
如还有遇到可以Ctrl+C两次中断下载，然后在临时文件夹中找到tasks.json并提供以便排查，感谢。临时文件路径会输出提示。

![image](https://github.com/Last-Order/Minyami/assets/3362825/5c214b2f-87a4-4899-b6ad-56b5e7f173c1)

**Comment by Hirumas** [comment]
升级版本突然就解决了，顺便打个卡
