### ISSUE TITLE
在下载中途一直403是因为什么原因

### ISSUE THREAD

**Issue by yingyingying670** [Last-Order/Minyami#119]
Downloading or decrypting 760000.ts failed. Retry later. [403 Forbidden] 报错代码是这个 下载到一部分之后会视频页面卡顿 然后出现这个代码 试了好几次都是在同一个地方卡顿

**Comment by yingyingying670** [comment]
我自己尝试了好久没办法了 只能来请教一下您。

**Comment by Last-Order** [comment]
Closed due to insufficient information.
