### ISSUE TITLE
通过 npm 更新时有奇怪的 warning 出现

### ISSUE THREAD

**Issue by DCxDESIGN** [Last-Order/Minyami#122]
**Basic Information**
* Node.js version: 21.5
* Minyami version: 5.0.2 -> 5.1.0

**Describe the bug**
在 Powershell 下使用 npm 进行包更新时，会出现奇怪的 warning
```
npm i -g minyami
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'minyami@5.1.0',
npm WARN EBADENGINE   required: { node: '~14 || ~16 || ~18 || ~20' },
npm WARN EBADENGINE   current: { node: 'v21.5.0', npm: '10.2.5' }
npm WARN EBADENGINE }

removed 73 packages, and changed 53 packages in 14s

1 package is looking for funding
  run `npm fund` for details
```

不是什么大问题，好像也没有什么实际影响，但印象里以前没有这个问题

**Comment by fireattack** [comment]
~~可以顺便把 readme 那个 node 版本的失效链接修了

https://nodejs.org/en/about/previous-releases -> https://nodejs.org/en/about/previous-releases

**Comment by Last-Order** [comment]
是因为尚未增加对 Node 21 的支持的声明，不影响使用。
下一个版本带上，谢谢报告。
