### ISSUE TITLE
DMM 公演回放不能下載 ~

### ISSUE THREAD

**Issue by MOMOKA88** [Last-Order/Minyami#129]
今天下載STU48 的回放公演時發現有一部公演不能用Minyami下載(只顯示""暂无数据")
用貓爪檢查連結是顯示manifest.mpd (如下圖) , 好像和其他不一樣 (其他都是m3u8)..
有辦法解決嗎?  謝謝

![未命名](https://github.com/Last-Order/Minyami/assets/132542834/4590b93b-6b2f-4334-a178-368ba81a8c1e)

**Comment by Last-Order** [comment]
谢谢 @pzhlkj6612 的解释。
Minyami 无支持 HLS 以外视频的计划。推荐您使用：https://github.com/nilaoda/N_m3u8DL-RE
