### ISSUE TITLE
NicoNico获取不到M3U8，无法下载录播

### ISSUE THREAD

**Issue by Andytaku** [Last-Order/Minyami#131]
Node.js版本：Node.js v20.12.2
Minyami版本：5.3.0
Minyami（Chrome扩展）：1.4.1
视频地址：https://live.nicovideo.jp/watch/lv345362732
![5](https://github.com/Last-Order/Minyami/assets/26221089/2e8ffdb5-f4c4-4757-b91f-3d08481cb159)
换了一个报错又不一样了
![2](https://github.com/Last-Order/Minyami/assets/26221089/f4507fde-3b6d-44cf-9bf1-76fd1d36f9b6)

**Comment by fireattack** [comment]
我可以下载，看着像网络问题。
代理挂了吗，加--verbose贴下log

**Comment by Andytaku** [comment]
是我这边TUN模式抽风了，可以下载了，谢谢
