### ISSUE TITLE
A key is needed to decrypt video but Minyami haven't got it. Please refresh and try again.

### ISSUE THREAD

**Issue by cchin-aim** [Last-Order/Minyami#136]
使用minyami的Chrome插件获取地址时，“该站点需要传递 Key 而 Minyami 没有拿到 请刷新重试”。刷新还是无法获取，视频可正常播放。

Node.js version: 20.17.0
Minyami version: 5.3.1
Minyami Extractor (Chrome Extension) version:1.1.17
Video URL: https://abema.tv/live-event/999b5691-78f3-45a3-9212-95ff97ed6014

**Comment by fireattack** [comment]
abema的ppv好像有DRM吧？minyami应该是不支持的，不清楚minyami 
（话说应该发在https://github.com/Last-Order/Minyami-chrome-extension/issues）

**Comment by Last-Order** [comment]
正如 fireattack 所说，Abema PPV 有 DRM，不在 Minyami 功能范围，请参见：https://github.com/Last-Order/Minyami/issues/116
