### ISSUE TITLE
niconico：Minyami Extrator 可能不支持此站点

### ISSUE THREAD

**Issue by HAYASHI-OPENAI** [Last-Order/Minyami#138]
请问大佬，在niconico使用minyami插件，显示“Minyami Extrator 可能不支持此站点，但是您可以手工获取 m3u8 地址尝试使用 minyami -d <url> 下载”

Node.js版本：Node.js v20.18.0
Minyami版本：5.4.0
Minyami（Chrome扩展）：当前最新版

我在所有niconico的视频都无法使用插件获取地址，包括会员限定视频。但是youtube的生放是可以正常获取m3u8的，想请教下是自己使用上的问题吗？

举例视频链接：https://www.nicovideo.jp/watch/sm41154392

**Comment by Last-Order** [comment]
浏览器扩展只支持部分站点，nico仅支持直播回放。未支持站点可以自行手动获取m3u8地址。

**Comment by HAYASHI-OPENAI** [comment]
感谢回复。我尝试了一个会员限定的生放回放
链接如下：https://live.nicovideo.jp/watch/lv346027563

成功在浏览器获取m3u8地址，但下载时提示：

[MINYAMI][INFO] Start fetching M3U8 file.
[MINYAMI][WARN] Fail to fetch M3U8 file: [ECONNRESET]
[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.
[MINYAMI][INFO] Try again.
[MINYAMI][WARN] Fail to fetch M3U8 file: [ECONNRESET]
[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.
[MINYAMI][INFO] Try again.
[MINYAMI][WARN] Fail to fetch M3U8 file: [ECONNRESET]
[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.
[MINYAMI][INFO] Try again.
[MINYAMI][WARN] Fail to fetch M3U8 file: [ECONNRESET]
[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.
[MINYAMI][INFO] Try again.
[MINYAMI][WARN] Fail to fetch M3U8 file: [ECONNRESET]
[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.
[MINYAMI][INFO] Try again.
[MINYAMI][WARN] Fail to fetch M3U8 file: [ECONNRESET]
[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.
[MINYAMI][WARN] Max retries exceeded. Abort.
[MINYAMI][ERROR] Aborted due to critical error.

请问是否是我什么的设置出现了问题呀

**Comment by Last-Order** [comment]
你需要给minyami设置代理，请参见：https://github.com/Last-Order/Minyami?tab=readme-ov-file#faq

**Comment by HAYASHI-OPENAI** [comment]
您好，我也有同时尝试--proxy和Proxifier的方式设置代理，错误代码是：

[MINYAMI][WARN] Downloading or decrypting 35000.ts failed. Retry later. [ERR_BAD_REQUEST]
[MINYAMI][WARN] Downloading or decrypting 15000.ts failed. Retry later. [ERR_BAD_REQUEST]
[MINYAMI][WARN] Downloading or decrypting 0000.ts failed. Retry later. [ERR_BAD_REQUEST]
[MINYAMI][WARN] Downloading or decrypting 50000.ts failed. Retry later. [ERR_BAD_REQUEST]
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] AxiosError: Request failed with status code 403
[MINYAMI][WARN] Downloading or decrypting 5000.ts failed. Retry later. [ERR_BAD_REQUEST]
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] AxiosError: Request failed with status code 403
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] AxiosError: Request failed with status code 403
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] AxiosError: Request failed with status code 403

**Comment by Last-Order** [comment]
nico下载出现部分报错是正常的，如果持续报错无进度请提供更完整的日志供排查~
