### ISSUE TITLE
Missing dependence

### ISSUE THREAD

**Issue by scqy2000** [Last-Order/Minyami#14]
卸载minyami再安装后就出现了
[MINYAMI][ERROR] Missing dependence: openssl
这个问题
但是OpenSSL确实处于正常状态
重新安装OpenSSL后仍存在问题

**Comment by Last-Order** [comment]
尝试运行一下`openssl version`可以得到正确的结果吗？

**Comment by scqy2000** [comment]
能得到正常反馈
LibreSSL 2.2.7

**Comment by Last-Order** [comment]
能告诉我系统版本吗 我去尝试复现一下

**Comment by scqy2000** [comment]
MacOs Higt Sierra 10.13.6

**Comment by Last-Order** [comment]
抱歉我无法复现该问题

**Comment by scqy2000** [comment]
![0030-10-04 18 50 36](https://user-images.githubusercontent.com/19802266/46469592-7a2e1700-c806-11e8-8682-b105b3b7a5ef.png)
不知道这是不是又是个bug，缺失OpenSSL那个只有在运行 minyami --clean时才出现。现在下载showroom又显示站点不支持

**Comment by Last-Order** [comment]
@scqy2000 直播下载需要加`--live`，因为sr没有回放下载所以显示不支持。

**Comment by scqy2000** [comment]
忘记了。试了其他网站，下载不存在影响。缺失OpenSSL缺失只有在执行minyami --clean时才会出现。估计是我自己电脑的问题吧。但是把相关的内容全部都重新安装一遍问题依然存在。
