### ISSUE TITLE
DOWNLOAD NICONICO ARCHIVE 403 ERROR / 下载NICONICO录播403ERROR

### ISSUE THREAD

**Issue by gyokusei** [Last-Order/Minyami#141]
Minyami version: 5.4.2
Os: Windows 11
Issue: Download niconico archive error / 下载niconico录播报错
Tried: Adjust threads to 1 and use resume mode but not works / 尝试限制并发到1以及使用恢复模式，不起作用

![image](https://github.com/user-attachments/assets/f067b612-5c93-498b-8136-48079a79b0a1)
![image](https://github.com/user-attachments/assets/593328ac-1840-4be8-bc64-236f1636acc6)
![8e358c1ed5d220c7002662baf7de98bb](https://github.com/user-attachments/assets/a3575982-c90d-45f0-b069-427e4bdee5e4)

**Comment by gyokusei** [comment]
看起来niconico检测到多开了，但我无论是关闭视频窗口，暂停视频播放，都没效果

**Comment by Last-Order** [comment]
请尝试使用原生日本IP。
