### ISSUE TITLE
使用minyami.user.js解析访问过的AbemaTV视频页必须清除浏览器缓存

### ISSUE THREAD

**Issue by Icyluna** [Last-Order/Minyami#16]
win10+chrome69+暴力猴
一旦浏览器曾经访问过需要解析的AbemaTV视频页，使用minyami.user.js都会提示“未能获取到 Key 如果该站点需要 Key 请刷新重试；刷新后请等待视频完全加载”。
无论是Ctrl+F5还是Disable cache均无法解决，必须清除浏览器的缓存才能正常解析，多次尝试均复现该问题。

**Comment by Last-Order** [comment]
无法复现。minyami.user.js 的全部功能不依赖 cookie 或 localStorage 所以我觉得是否再次访问应该没有关系。

请确认一下，无法获取时是不是 Abema 使用了 Flash 播放器？Flash 播放器无法获取到是正常情况。

**Comment by Icyluna** [comment]
确认了一下是html5播放器，我稍后换一下环境再做尝试。
