### ISSUE TITLE
该站点需要传递 Key 而 Minyami 没有拿到 请刷新重试

### ISSUE THREAD

**Issue by scqy2000** [Last-Order/Minyami#18]
**Basic Information**今天在使用minyami的Chrome插件获取地址时，无法获取，一直显示“该站点需要传递 Key 而 Minyami 没有拿到 请刷新重试”。刷新还是无法获取，视频可正常播放
* Node.js version: 11.9.0
* Minyami version: 2.1.11
* Minyami Extractor (Chrome Extension) version:1.0.12
* Video URL: https://abema.tv/video/episode/90-1209_s15_p1004

**Comment by Last-Order** [comment]
AbemaTV 今天中午改版了，请静候更新

**Comment by Last-Order** [comment]
chrome 扩展 1.0.13 已提交商店审核，应该修正了，还有问题请留言。
