### ISSUE TITLE
Nico好像又死了

### ISSUE THREAD

**Issue by ruixingw** [Last-Order/Minyami#19]
**Basic Information**
* Node.js version: v10.15.1
* Minyami version: 2.1.14
* Minyami Extractor (Chrome Extension) version: 1.0.14
* Video URL: http://live2.nicovideo.jp/watch/lv318258384
视频前半段公开，最后30分钟是会员限定。

**Describe the bug**
正常下载前几十个chunk后（就一两秒）报错并提示403。
尝试了--threads 1故障依旧。
恢复模式-r也会立刻403退出。

[MINYAMI][WARN] Downloading or decrypting 215266.ts failed. Retry later.
[MINYAMI][WARN] Downloading or decrypting 205266.ts failed. Retry later.
[MINYAMI][WARN] Downloading or decrypting 200266.ts failed. Retry later.
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 403
[MINYAMI][WARN] Downloading or decrypting 225266.ts failed. Retry later.
[MINYAMI][WARN] Downloading or decrypting 220266.ts failed. Retry later.
[MINYAMI][WARN] Downloading or decrypting 230266.ts failed. Retry later.
[MINYAMI][WARN] Downloading or decrypting 235266.ts failed. Retry later.
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 403
[MINYAMI][WARN] Downloading or decrypting 240266.ts failed. Retry later.
[MINYAMI][WARN] Downloading or decrypting 250266.ts failed. Retry later.
[MINYAMI][WARN] Downloading or decrypting 255266.ts failed. Retry later.
[MINYAMI][WARN] Downloading or decrypting 245266.ts failed. Retry later.
[MINYAMI][WARN] Downloading or decrypting 260266.ts failed. Retry later.
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 403
[MINYAMI][WARN] Downloading or decrypting 275266.ts failed. Retry later.
[MINYAMI][WARN] Downloading or decrypting 265266.ts failed. Retry later.
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 403
[MINYAMI][WARN] Downloading or decrypting 280266.ts failed. Retry later.
[MINYAMI][WARN] Downloading or decrypting 285266.ts failed. Retry later.

**Comment by Last-Order** [comment]
嗯 知道了已经 目前没啥思路 可能需要点时间修
恢复模式的话你需要刷新网页获得一个新的地址然后使用

**Comment by Last-Order** [comment]
最新版本的表现如何，需要大家反馈一下

**Comment by ruixingw** [comment]
随便点开了一个直播试了试，看来还是有问题

[MINYAMI][INFO] M3U8 file fetched.
[MINYAMI][INFO] Proccessing 124257.ts finished. (31 / unknown | Avg Speed: 1.82 chunks/s or 0.91x)
[MINYAMI][INFO] Proccessing 124256.ts finished. (32 / unknown | Avg Speed: 1.88 chunks/s or 0.94x)
[MINYAMI][INFO] Start fetching M3U8 file.
[MINYAMI][WARN] Fail to fetch M3U8 file: [403 Forbidden]
[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.
[MINYAMI][INFO] Try again.
[MINYAMI][WARN] Fail to fetch M3U8 file: [403 Forbidden]
[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.
[MINYAMI][INFO] Try again.
[MINYAMI][WARN] Downloading or decrypting 124258.ts failed. Retry later.
[MINYAMI][WARN] Processing 124258.ts failed.
[MINYAMI][WARN] Downloading or decrypting 124259.ts failed. Retry later.
[MINYAMI][WARN] Processing 124259.ts failed.
[MINYAMI][WARN] Fail to fetch M3U8 file: [403 Forbidd

**Comment by Last-Order** [comment]
这个不算……刷新下再试试（）

**Comment by ruixingw** [comment]
开issue时的那个是回放，不过昨天是随便点开了一个直播测试（首页上没找到免费回放的视频……）
下次用到了再试试

谢谢修复
