### ISSUE TITLE
建议:增加 header 的支持

### ISSUE THREAD

**Issue by shetz163** [Last-Order/Minyami#20]
遇到一个网站在拉取m3u8的时候会判定 Origin 和 Referer 是否来源于网站,现在先把m3u8下载了之后,用node开一个web服务再用minyami取的m3u8,或者能否支持读取本地的m3u8文件呢?

**Comment by Last-Order** [comment]
Minyami 支持本地 m3u8 ，但是多数网站 m3u8 中的视频路径使用相对路径，本地 m3u8 无法被正确处理。
我会加入一个 `--header` 选项支持自定义 header

**Comment by Last-Order** [comment]
added in 2.1.16

**Comment by railannad** [comment]
请问headers的格式要怎么写呢？
`{"aaa":"aaa","bbb":"bbb"}` 这样？

**Comment by tuzi3040** [comment]
help里都有写
