### ISSUE TITLE
Nico的Timeshift无法正常录制

### ISSUE THREAD

**Issue by Etherrrr** [Last-Order/Minyami#21]
**Basic Information**
* Node.js version: v10.15.1
* Minyami version: 2.1.15
* Minyami Extractor (Chrome Extension) version: 1.0.16
* Video URL: https://live2.nicovideo.jp/watch/lv318716514 https://live2.nicovideo.jp/watch/lv318731640

**Describe the bug**

与#19 类似，在录制Timeshift的过程中，最开始的部分chunk可以正常录制，后半部分出现大量的报错，无法正常录制。
```
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 403.
[MINYAMI][WARN] Downloading or decrypting 420466.ts failed. Retry later.
```
目前最新的版本仍然无法正常录制，想问一下有什么解决办法吗？
**Screenshots**
![Snipaste_2019-03-09_15-37-27](https://user-images.githubusercontent.com/20717049/54067938-448fcd00-4281-11e9-8267-9cb19e33a24f.png)

**Comment by Last-Order** [comment]
草 巧了 这视频我也下过

**Comment by Last-Order** [comment]
Should be fixed in 2.1.16.

**Comment by ruixingw** [comment]
https://live2.nicovideo.jp/watch/lv318900314
fyi 这个视频还是会有问题，不过每次能下载~150个chunk，用恢复模式重复十几次倒是就下载完了（捂脸）

**Comment by Last-Order** [comment]
@ruixingw 好的我会看看。（下次的话可以开一个新的issue，这样不会打扰到这个issue的楼主）

**Comment by Last-Order** [comment]
@ruixingw 我推测是因为 Websocket 连接并没有走代理的原因，在新的版本我让他走代理了（如果指定了代理），看看会不会有改善。

**Comment by ruixingw** [comment]
> 
> 
> @ruixingw 我推测是因为 Websocket 连接并没有走代理的原因，在新的版本我让他走代理了（如果指定了代理），看看会不会有改善。

并没有用代理……我是在本机chrome上获取了命令之后，ssh到我租的一个日本服务器上运行的minyami
需要的话可以私信提供该服务器的登录密码（平常只用来挂代理 并没什么重要信息）

**Comment by ruixingw** [comment]
@Last-Order 不过还有一点，这个视频本身是部分会员限定的 ，大约35~50分以及大约1:30:00之后 都是会员限定，不入会是看不到的。有可能是因为这个的缘故？
不过按上面说的多次使用恢复模式倒是可以地完整下载下来（包括会员限定部分，当然是登录之后获取的key）

**Comment by Last-Order** [comment]
@ruixingw 会员限定是没有关系的（限定部分会是另外一个流）。所以你的问题我并不能复现出来，无论是在Linux还是Windows，而且我感觉和这也没啥关系.. 如果你可以在你服务器稳定复现的话……可以试试（我的邮箱-> sora@sound.moe

**Comment by ruixingw** [comment]
> 
> 
> @ruixingw 会员限定是没有关系的（限定部分会是另外一个流）。所以你的问题我并不能复现出来，无论是在Linux还是Windows，而且我感觉和这也没啥关系.. 如果你可以在你服务器稳定复现的话……可以试试（我的邮箱-> [sora@sound.moe](mailto:sora@sound.moe)

已发，多谢。
