### ISSUE TITLE
GYAO走代理的时候会报404

### ISSUE THREAD

**Issue by shetz163** [Last-Order/Minyami#23]
**Basic Information**
* Node.js version: 10.12.0
* Minyami version: 2.1.17
* Minyami Extractor (Chrome Extension) version:1.1.2
* Video URL: https://vod01-gyao.c.yimg.jp/4235717419001/6021924662001/4235717419001_6021924662001_6021072921001.m3u8

**To Reproduce**
命令:minyami -d "https://vod01-gyao.c.yimg.jp/4235717419001/6021924662001/4235717419001_6021924662001_6021072921001.m3u8" --proxy "127.0.0.1:1080"
在使用代理之后会报 [404 Not Found on Accelerator]
但同时间用chrome设置代理并打开这个m3u8(安装了HLS插件)则可以正常播放
代理下载其他网站如abematv正常
使用(chrome应用版本的)postman走代理访问m3u8也是正常读取的
而同一个m3u8不使用代理能正常打开并且下载,只是速度太慢
不知道是否是因为GYAO设置了新的拦截方式导致的

**Comment by Last-Order** [comment]
嗯哼，请先用第三方工具（如proxifier）代理一下来解决这个问题，后续会修正。

**Comment by shetz163** [comment]
最后用路由器翻墙暂时解决了这个问题

**Comment by Last-Order** [comment]
2.1.18 应该已经修复了这个问题
