### ISSUE TITLE
NicoTS似乎又不好用了

### ISSUE THREAD

**Issue by Etherrrr** [Last-Order/Minyami#24]
**Basic Information**
* Node.js version: 11.14.0
* Minyami version: 2.2.3
* Minyami Extractor (Chrome Extension) version: 1.1.4
* Video URL: https://live2.nicovideo.jp/watch/lv319958910

**Describe the bug**
依旧是能够录制前几个chunk，而后大量报403

**Comment by Last-Order** [comment]
我这没什么问题。

保证你到nico之间访问流畅……然后播放器画质记得选最高。有问题再reopen。
