### ISSUE TITLE
請問關於輸出成MKV格式

### ISSUE THREAD

**Issue by kof11** [Last-Order/Minyami#26]
https://i.imgur.com/12YpcQQ.jpg
我明明有將mkvmerge添加到系统变量了，為何它還是顯示無法輸出成MKV呢？

**Comment by Last-Order** [comment]
再加个--format mkv




------------------ 原始邮件 ------------------
发件人: "kof11"<notifications@github.com>;
发送时间: 2019年6月5日(星期三) 下午4:41
收件人: "Last-Order/Minyami"<Minyami@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Last-Order/Minyami] 請問關於輸出成MKV格式 (#26)




https://i.imgur.com/12YpcQQ.jpg
 我明明有將mkvmerge添加到系统变量了，為何它還是顯示無法輸出成MKV呢？
