### ISSUE TITLE
[MINYAMI][ERROR] Fail to merge video. Please merge video chunks manually.

### ISSUE THREAD

**Issue by chakfung2** [Last-Order/Minyami#29]
最後會出現TS檔，能播放。
如果改成.mkv，加--format mkv，就會出現一個5KB的mkv檔案。

H:\Minyami_Download>minyami -d "https://ds-vod-abematv.akamaized.net/program/90-483_s0_p74/1080/playlist.m3u8?aver=0&ccf=11&dt=pc_unknown&enc=clear" --output "指原莉乃＆ブラマヨの恋するサイテー男総選挙 - #74：アートの秋！汚れた部屋に裸体♡  【Abemaビデオ】見逃した番組や人気作品が見放題.ts" --key "b4cce31e26ba80da794b0d7510095a00"
[MINYAMI][INFO] Start fetching M3U8 file.
[MINYAMI][INFO] M3U8 file fetched.
[MINYAMI][INFO] Site comfirmed: AbemaTV.
[MINYAMI][INFO] Key: b4cce31e26ba80da794b0d7510095a00; IV: 63d92ac3a2e8eefa4591a52b705b73a4.
[MINYAMI][INFO] Start downloading with 5 thread(s).
[MINYAMI][INFO] Proccessing 4ueVDyTwKddJed52zasBf3F8VC43FZTmS.ts finished. (1 / 419 or 0.24% | Avg Speed: 0.50 chunks/s or 2.51x | ETA: 13m 11s)
...(太长我不全部贴上来了)...
[MINYAMI][INFO] Proccessing 3hT1hh2ksE3rsrEKKz9q1oye9pCq2zGUC.ts finished. (419 / 419 or 100.00% | Avg Speed: 2.67 chunks/s or 13.42x | ETA: 0s)
[MINYAMI][INFO] All chunks downloaded. Start merging chunks.
[MINYAMI][INFO] Downloaded: 419; Waiting for download: 0
[MINYAMI][INFO] End of merging.
[MINYAMI][INFO] Starting cleaning temporary files.
[MINYAMI][INFO] Saving task status.
[MINYAMI][INFO] Downloaded: 419; Waiting for download: 0
[MINYAMI][INFO] Please wait.
Error: Command failed: rd /s /q C:\Users\**(實名不方便貼出來,長這個樣子Aaaa Bbbb Ccc)**\AppData\Roaming\npm\node_modules\minyami\temp_1562484476435
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the path specified.

    at ChildProcess.exithandler (child_process.js:297:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  killed: false,
  code: 3,
  signal: null,
  cmd: 'rd /s /q C:\\Users\\**(實名不方便貼出來,長這個樣子Aaaa Bbbb Ccc)**\\AppData\\Roaming\\npm\\node_modules\\minyami\\temp_1562484476435',
  stdout: '',
  stderr: 'The system cannot find the file specified.\r\n' +
    'The system cannot find the file specified.\r\n' +
    'The system cannot find the path specified.\r\n'
}
[MINYAMI][ERROR] Fail to merge video. Please merge video chunks manually.

**Comment by Last-Order** [comment]
如果你使用`--format mkv`，那么你的`--output`应该以`.mkv`结尾；试一下，还有问题请继续留言。
你的报错是因为删除临时目录失败导致的。你可以使用`minyami --clean`手动清理一下试试。

**Comment by chakfung2** [comment]
1.「使用minyami --clean」
會出現The system cannot find the path specified.
但是資料夾是存在的
![image](https://user-images.githubusercontent.com/19611128/60765929-849e7980-a0d4-11e9-96af-041b045ab00a.png)
所以我直接去以上路徑刪除。

H:\Minyami_Download>minyami clean
[MINYAMI][INFO] Error: Command failed: rd /s /q C:\Users\**(實名不方便貼出來,長這個樣子Aaaa Bbbb Ccc)**\AppData\Roaming\npm\node_modules\minyami\temp_1562487071685
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the path specified.

(node:7152) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[MINYAMI][INFO] Error: Command failed: rd /s /q C:\Users\**(實名不方便貼出來,長這個樣子Aaaa Bbbb Ccc)**\AppData\Roaming\npm\node_modules\minyami\temp_1562486808013
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the path specified.

[MINYAMI][INFO] Error: Command failed: rd /s /q C:\Users\**(實名不方便貼出來,長這個樣子Aaaa Bbbb Ccc)**\AppData\Roaming\npm\node_modules\minyami\temp_1562486378529
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the path specified.

[MINYAMI][INFO] Error: Command failed: rd /s /q C:\Users\**(實名不方便貼出來,長這個樣子Aaaa Bbbb Ccc)**\AppData\Roaming\npm\node_modules\minyami\temp_1562486103585
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the path specified.

[MINYAMI][INFO] Error: Command failed: rd /s /q C:\Users\**(實名不方便貼出來,長這個樣子Aaaa Bbbb Ccc)**\AppData\Roaming\npm\node_modules\minyami\temp_1562485756326
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the path specified.

[MINYAMI][INFO] Error: Command failed: rd /s /q C:\Users\**(實名不方便貼出來,長這個樣子Aaaa Bbbb Ccc)**\AppData\Roaming\npm\node_modules\minyami\temp_1562485739666
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the path specified.

[MINYAMI][INFO] Error: Command failed: rd /s /q C:\Users\**(實名不方便貼出來,長這個樣子Aaaa Bbbb Ccc)**\AppData\Roaming\npm\node_modules\minyami\temp_1562485718208
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the path specified.

[MINYAMI][INFO] Error: Command failed: rd /s /q C:\Users\**(實名不方便貼出來,長這個樣子Aaaa Bbbb Ccc)**\AppData\Roaming\npm\node_modules\minyami\temp_1562485482660
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the path specified.

[MINYAMI][INFO] Error: Command failed: rd /s /q C:\Users\**(實名不方便貼出來,長這個樣子Aaaa Bbbb Ccc)**\AppData\Roaming\npm\node_modules\minyami\temp_1562485036703
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the path specified.

[MINYAMI][INFO] Error: Command failed: rd /s /q C:\Users\**(實名不方便貼出來,長這個樣子Aaaa Bbbb Ccc)**\AppData\Roaming\npm\node_modules\minyami\temp_1562484476435
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the path specified.

[MINYAMI][INFO] Error: Command failed: rd /s /q C:\Users\**(實名不方便貼出來,長這個樣子Aaaa Bbbb Ccc)**\AppData\Roaming\npm\node_modules\minyami\temp_1562483936029
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the path specified.

[MINYAMI][INFO] Error: Command failed: rd /s /q C:\Users\**(實名不方便貼出來,長這個樣子Aaaa Bbbb Ccc)**\AppData\Roaming\npm\node_modules\minyami\temp_1562487359191
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the path specified.

[MINYAMI][INFO] Error: Command failed: rd /s /q C:\Users\**(實名不方便貼出來,長這個樣子Aaaa Bbbb Ccc)**\AppData\Roaming\npm\node_modules\minyami\temp_1562487590588
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the path specified.

2. 「如果你使用--format mkv，那么你的--output应该以.mkv」
我之前已經試了, 不過沒有貼出來。會出現一個5KB的mkv檔案, 不能播放。
我直接去以上1.圖中的路徑刪除temp的資料夾。再試了一次。都是一樣的error，一樣會出現一個5KB的mkv檔案, 不能播放。

H:\Minyami_Download>minyami -d "https://ds-vod-abematv.akamaized.net/program/90-483_s0_p82/1080/playlist.m3u8?aver=0&ccf=11&dt=pc_unknown&enc=clear" --output "指原莉乃＆ブラマヨの恋するサイテー男総選挙 - #82：セクシー女優に俺の甘えテク披露♡  【Abemaビデオ】見逃した番組や人気作品が見放題.mkv" --format mkv --key "eca40a57a85b3aa7fba94809e5d96224"
[MINYAMI][INFO] Start fetching M3U8 file.
[MINYAMI][INFO] M3U8 file fetched.
[MINYAMI][INFO] Site comfirmed: AbemaTV.
[MINYAMI][INFO] Key: eca40a57a85b3aa7fba94809e5d96224; IV: 8e412b9557687d6ab6675f4ec47cb384.
[MINYAMI][INFO] Start downloading with 5 thread(s).
[MINYAMI][INFO] Proccessing BMSs7U8JnYws3h9kiVW2si6SUci3Zppxt.ts finished. (1 / 439 or 0.23% | Avg Speed: 0.50 chunks/s or 2.51x | ETA: 11m 58s)
[MINYAMI][INFO] Proccessing Bh4oTgarVKsVjCaGznmhCR11iiFaZfqkg.ts finished. (2 / 439 or 0.46% | Avg Speed: 1.00 chunks/s or 5.03x | ETA: 6m 1s)
...(太长我不全部贴上来了)...
[MINYAMI][INFO] Proccessing F7jFahJChi9QhHyVbGFwaJTnhyaG8ky6o.ts finished. (438 / 439 or 99.77% | Avg Speed: 2.56 chunks/s or 12.88x | ETA: 0s)
[MINYAMI][INFO] Proccessing QDoQfwToU2S5wjhjwSwV85SvjvewVuAcU.ts finished. (439 / 439 or 100.00% | Avg Speed: 2.54 chunks/s or 12.76x | ETA: 0s)
[MINYAMI][INFO] All chunks downloaded. Start merging chunks.
[MINYAMI][INFO] Downloaded: 439; Waiting for download: 0
[MINYAMI][INFO] End of merging.
[MINYAMI][INFO] Starting cleaning temporary files.
[MINYAMI][INFO] Saving task status.
[MINYAMI][INFO] Downloaded: 439; Waiting for download: 0
[MINYAMI][INFO] Please wait.
Error: Command failed: rd /s /q C:\Users\\**(實名不方便貼出來,長這個樣子Aaaa Bbbb Ccc)**\AppData\Roaming\npm\node_modules\minyami\temp_1562488559921
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the path specified.

    at ChildProcess.exithandler (child_process.js:297:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  killed: false,
  code: 3,
  signal: null,
  cmd: 'rd /s /q C:\\Users\\\**(實名不方便貼出來,長這個樣子Aaaa Bbbb Ccc)**\\AppData\\Roaming\\npm\\node_modules\\minyami\\temp_1562488559921',
  stdout: '',
  stderr: 'The system cannot find the file specified.\r\n' +
    'The system cannot find the file specified.\r\n' +
    'The system cannot find the path specified.\r\n'
}
[MINYAMI][ERROR] Fail to merge video. Please merge video chunks manually.

**Comment by Last-Order** [comment]
1. 所以你的系统用户名是含有空格吗？
2. 请告诉我你的`mkvmerge`版本（我觉得可能是因为你的`mkvmerge`版本过低）
（顺便一提，hls视频使用mkv合并会带来音画不同步等问题，建议使用ts，后续可以自己再重新封装mp4等格式

**Comment by chakfung2** [comment]
1. 是的，用户名含有空格。所以导致删除临时目录失败嗎?
2. mkvmerge版本是29.0.0。我換個35.0.0(應該是目前最新)試了都是一樣。不過如果會有音画不同步的問題的話, 不要緊了, 有時間的話我再自己封装mp4吧。用ffmpeg -c copy應該沒問題吧?

**Comment by Last-Order** [comment]
1. 这应该是个bug，后续版本修正。
2. 这个问题我晚些时候看看。`ffmpeg -c copy`->没问题的。

**Comment by lidoworld** [comment]
强烈不建议使用.mkv输出，由于精度问题，包括Abema在内的平台视频出现了很多的问题
原本Minyami也是默认用.mkv，不然为什么改.ts

**Comment by Last-Order** [comment]
关于路径空格问题应该已经在`2.2.8`修复。

关于 mkv 生成问题，我认为是 mkvtoolnix 方面的问题，已经提报 issue，等待对方回复。

跟踪：https://gitlab.com/mbunkus/mkvtoolnix/issues/2583

**Comment by Last-Order** [comment]
Abema 的文件中既不包含 PAT 也不包含 PMT，因此 mkvtoolnix 方面表示不支持也没有计划支出。

故 minyami 也不会支持。
