### ISSUE TITLE
/usr/bin/env: ‘node\r’: No such file or directory

### ISSUE THREAD

**Issue by LoveCany** [Last-Order/Minyami#31]
**Basic Information**
* Node.js version: 8.10.0
* Minyami version: 2.2.8

可能为源代码在windows环境下写入导致在ubuntu环境下无法正常执行，希望解决该问题。

**Comment by Last-Order** [comment]
Minyami 在设计上即可在 Linux 环境运行，并有相关处理
![image](https://user-images.githubusercontent.com/3362825/62822924-ea42c180-bbbc-11e9-989e-623aab1c5c37.png)

Readme中写到：! Minyami requires Node 10.5.0+

请升级后再试试

**Comment by Last-Order** [comment]
Close issue due to lack of response. Feel free to reopen.

**Comment by Yesterday17** [comment]
今天我也遇到了...

系统信息:
```
操作系统： Manjaro Linux 
KDE Plasma 版本： 5.16.4
KDE 框架版本： 5.60.0
Qt 版本： 5.13.0
内核版本： 4.19.62-1-MANJARO
操作系统类型： 64-位
处理器： 12 × Intel® Core™ i7-8750H CPU @ 2.20GHz
内存： 15.5 GiB 内存
```

NodeJS版本: `v11.15.0`

![image](https://user-images.githubusercontent.com/8667822/63135775-a1966880-c001-11e9-82c8-0e1ab8a09e86.png)

据 [stackoverflow](https://stackoverflow.com/questions/18492897/env-node-r-no-such-file-or-directory-with-cordova-cli) 说好像是在 `#!/usr/bin/env node` 最后有 `\r` 引起的...

一劳永逸的办法还是直接 CRLF -> LF(

**Comment by Last-Order** [comment]
fixed in 2.2.9

**Comment by Last-Order** [comment]
谢谢，2.2.10应该修正了。我修改了构建脚本。
