### ISSUE TITLE
Minyami still remind to set key to download Abematv video on PowerShell

### ISSUE THREAD

**Issue by LoveCany** [Last-Order/Minyami#35]
**Basic Information**
* Node.js version: 10.16.0
* Minyami version: 2.2.15
* Minyami Extractor (Chrome Extension) version:1.1.6
* Video URL: https://abema.tv/video/episode/221-57_s1_p1

**Describe the bug**
I have set the key of Abematv, but Minyami still remind me to set the key to download the video.
I have tried to use PowerShell and CMD on Windows, it failed on PowerShell but succeed on CMD.
Command:  minyami -d "https://ds-vod-abematv.akamaized.net/program/221-57_s1_p1/1080/playlist.m3u8?aver=3&ccf=0&dt=pc_chrome&enc=clear" --output "ファンタ坂学園と大合唱計画 - 本編 - ファンタ坂学園と大合唱計画 #1  【Abemaビデオ】見逃した番組や人気作品が見放題.ts" --key "1d8cf631a8380f9510b5e76141e1a700" 

[MINYAMI][INFO] Start fetching M3U8 file.                                                                               [MINYAMI][INFO] M3U8 file fetched.                                                                                      [MINYAMI][INFO] Site comfirmed: AbemaTV.                                                                                Error To download AbemaTV, you need to set a key manually Error: To download AbemaTV, you need to set a key manually        at Function.parse (C:\Users\**\AppData\Roaming\npm\node_modules\minyami\dist\core\parsers\abema.js:7:19)             at ArchiveDownloader.<anonymous> (C:\Users\**\AppData\Roaming\npm\node_modules\minyami\dist\core\archive.js:74:36)                                                                                                                           at Generator.next (<anonymous>)                                                                                         at fulfilled (C:\Users\**\AppData\Roaming\npm\node_modules\minyami\dist\core\archive.js:5:58)                        at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by Last-Order** [comment]
Hi, please use cmd instead of powershell. This is a problem of Node & npm and I can do nothing with it.

**Comment by tuzi3040** [comment]
You may use pwsh but you have to escape `&` char in the url string by using `'"{url}"'`.
Details here at: Last-Order/Minyami-chrome-extension#17.
