### ISSUE TITLE
【niconico live】Fail to fetch M3U8 file: [ECONNRESET]

### ISSUE THREAD

**Issue by LzNOHentai** [Last-Order/Minyami#37]
**Basic Information**
* Node.js version: 12.2.0
* Minyami version: 2.2.18
* Minyami Extractor (Chrome Extension) version:1.1.7
* Video URL: https://live2.nicovideo.jp/watch/lv323134207

cmd已使用set http_proxy和https_proxy挂上代理，浏览器可正常观看，有会员、选择3Mbps线路。
无法抓流，出现以下警告：
[MINYAMI][INFO] Start fetching M3U8 file.
[MINYAMI][WARN] Fail to fetch M3U8 file: [ECONNRESET]
[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.
如果不挂代理则超时。
直播时使用直播模式抓流也是同样的警告，现在下录播也不行。

**Comment by Last-Order** [comment]
Minyami只支持socks代理 使用 --proxy "<host>:<port>"来设置代理

例如

`minyami -d "xxxxxx.m3u8" --proxy "127.0.0.1:1080"`

**Comment by LzNOHentai** [comment]
> Minyami只支持socks代理 使用` --proxy "<host>:<port>"`来设置代理
> 
> 例如
> 
> `minyami -d "xxxxxx.m3u8" --proxy "127.0.0.1:1080"`

啊，我想起来了，太久没用都忘记了这个要用自己的proxy命令……感谢回复，抱歉打扰了~
现在是顺利在下载，不过经常跳403，虽然这个可能有我网络的原因在。

**Comment by Last-Order** [comment]
Nico下载出现403是正常的 可以不理会
