### ISSUE TITLE
如何提前停止下载live?

### ISSUE THREAD

**Issue by fireattack** [Last-Order/Minyami#40]
**Basic Information**
* Node.js version: 12.1-.0
* Minyami version: 2.2.15
* Minyami Extractor (Chrome Extension) version:
* Video URL: 任意y2b直播

**Describe the bug**

我测试了下，如果按ctrl+C，会显示“已经按下ctrl+C，等待task结束”，但是会依然继续不停下载；如果再按一次，会强制停止，但是已经下载完成的部分直接就被清理掉了。

**Comment by Last-Order** [comment]
Ctrl+C一次是你想要的功能。等待任务完成指的是按下Ctrl+C前获取到的任务。

"但是已经下载完成的部分直接就被清理掉了。"←3.0.1修正了这个逻辑，强制退出不会清理临时文件了。

**Comment by fireattack** [comment]
我先更新下试试

**Comment by fireattack** [comment]
呃，好像还是不太是我想要的

>等待任务完成指的是按下Ctrl+C前获取到的任务

对于`--live`，似乎就无限继续下去了？

>不会清理临时文件了。

没清理掉的文件是要自己手动导出合并？有没有可能提前停止就把现在已经下载的部分吐出来合并，就像youtube-dl那样

**Comment by Last-Order** [comment]
并不会继续下载……只会完成现在应该完成的任务……你可以多等一会儿……
Minyami不是顺序下载的，直接结束无法输出文件

**Comment by fireattack** [comment]
已经等了十几分钟了(bgm38) 是我哪里操作不对么 参见下面的gif


![gifski2](https://user-images.githubusercontent.com/4130991/74095223-49718800-4ab3-11ea-9551-0fa08f33d88b.gif)

**Comment by Last-Order** [comment]
如果这个直播开启了DVR（实时回放），那么Minyami是从回放的起点开始下载的（进度条开头）。
按一次Ctrl+C的结果就是你会得到进度条开头到你按下Ctrl+C的时刻的这一段视频。在开启DVR的直播里需要更多时间来完成当前任务，因为一般会有很多块等着下。

**Comment by fireattack** [comment]
噢噢 明白了
