### ISSUE TITLE
下载一定要保持页面打开吗

### ISSUE THREAD

**Issue by wwh1004** [Last-Order/Minyami#41]
**Basic Information**
* Node.js version:  v12.3.1
* Minyami version:  v3.0.2
* Minyami Extractor (Chrome Extension) version: 1.1.9
* Video URL:  任意直播

**Describe the bug**
插件勾了下载直播，用的是自己的机场，ip不会变的。似乎下载一定要保持页面打开，浏览器开着nicolive的页面用minyami下载live就没问题。如果关了页面，大概下载200 300 chunks后就403 forbidden了。

[MINYAMI][WARN] Fail to fetch M3U8 file: [403 Forbidden]
[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.
[MINYAMI][INFO] Try again.
[MINYAMI][WARN] Fail to fetch M3U8 file: [403 Forbidden]
[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.
[MINYAMI][INFO] Try again.
[MINYAMI][WARN] Downloading or decrypting 70749.ts failed. Retry later. [403 Forbidden]
[MINYAMI][WARN] Processing 70749.ts failed.
[MINYAMI][WARN] Downloading or decrypting 70748.ts failed. Retry later. [403 Forbidden]
[MINYAMI][WARN] Processing 70748.ts failed.
[MINYAMI][WARN] Fail to fetch M3U8 file: [403 Forbidden]
[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.
[MINYAMI][INFO] Try again.
[MINYAMI][WARN] Downloading or decrypting 70749.ts failed. Retry later. [403 Forbidden]
[MINYAMI][WARN] Processing 70749.ts failed.
[MINYAMI][WARN] Downloading or decrypting 70748.ts failed. Retry later. [403 Forbidden]
[MINYAMI][WARN] Processing 70748.ts failed.
[MINYAMI][WARN] Fail to fetch M3U8 file: [403 Forbidden]
[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.
[MINYAMI][WARN] Max retries exceeded. Abort.

**Comment by Last-Order** [comment]
因为websocket断掉了 是网络问题 
说实话nico直播没什么好录的 建议下timeshift
