### ISSUE TITLE
下载卡在最后部分

### ISSUE THREAD

**Issue by gellneko** [Last-Order/Minyami#42]
**Basic Information**
* Node.js version: v12.16.1
* Minyami version: 3.0.2
* Minyami Extractor (Chrome Extension) version: 1.1.9
* Video URL: https://live2.nicovideo.jp/watch/lv323870210

**Describe the bug**
类似于https://github.com/Last-Order/Minyami/issues/36 的问题，不过有nico的普雷米会员、live本身有付过费、也手动选了最高画质，但是下载的时候一直都卡在最后部分（2070/2071）并报错403。
以及在2070/2071的时候按下ctrl+c的话没有任何ts文件输出，重开后也在继续403报错。
基本和https://github.com/Last-Order/Minyami/issues/21 一样，不过里面提到v2.1.16应该修好了下载普通Timeshift的部分，但是有阅览限制的视频问题似乎还是存在……？

[MINYAMI][INFO] Proccessing 10215066.ts finished. (2069 / 2071 or 99.90% | Avg Speed: 2.92 chunks/s or 14.61x | ETA: 1s)
[MINYAMI][INFO] Proccessing 10210066.ts finished. (2070 / 2071 or 99.95% | Avg Speed: 2.92 chunks/s or 14.60x | ETA: 0s)
[MINYAMI][INFO] Chunk group action <ping> finished.
[MINYAMI][WARN] Downloading or decrypting 10350066.ts failed. Retry later. [403 Forbidden]
[MINYAMI][INFO] Chunk group action <ping> finished.
[MINYAMI][WARN] Downloading or decrypting 10350066.ts failed. Retry later. [403 Forbidden]
[MINYAMI][INFO] Chunk group action <ping> finished.
[MINYAMI][WARN] Downloading or decrypting 10350066.ts failed. Retry later. [403 Forbidden]
[MINYAMI][INFO] Chunk group action <ping> finished.
[MINYAMI][WARN] Downloading or decrypting 10350066.ts failed. Retry later. [403 Forbidden]
[MINYAMI][INFO] Chunk group action <ping> finished.
[MINYAMI][WARN] Downloading or decrypting 10350066.ts failed. Retry later. [403 Forbidden]
[MINYAMI][INFO] Chunk group action <ping> finished.
[MINYAMI][WARN] Downloading or decrypting 10350066.ts failed. Retry later. [403 Forbidden]
[MINYAMI][INFO] Chunk group action <ping> finished.
[MINYAMI][WARN] Downloading or decrypting 10350066.ts failed. Retry later. [403 Forbidden]
[MINYAMI][INFO] Chunk group action <ping> finished.
[MINYAMI][WARN] Downloading or decrypting 10350066.ts failed. Retry later. [403 Forbidden]
[MINYAMI][INFO] Chunk group action <ping> finished.
[MINYAMI][WARN] Downloading or decrypting 10350066.ts failed. Retry later. [403 Forbidden]
[MINYAMI][INFO] Chunk group action <ping> finished.
[MINYAMI][WARN] Downloading or decrypting 10350066.ts failed. Retry later. [403 Forbidden]
[MINYAMI][INFO] Chunk group action <ping> finished.
[MINYAMI][WARN] Downloading or decrypting 10350066.ts failed. Retry later. [403 Forbidden]
[MINYAMI][INFO] Chunk group action <ping> finished.
[MINYAMI][WARN] Downloading or decrypting 10350066.ts failed. Retry later. [403 Forbidden]
[MINYAMI][INFO] Chunk group action <ping> finished.

![error](https://user-images.githubusercontent.com/61431488/75184179-d3972e80-56f8-11ea-8c7a-e0cf0afb18f6.png)

[MINYAMI][INFO] Chunk group action <ping> finished.
[MINYAMI][WARN] Downloading or decrypting 10350066.ts failed. Retry later. [403 Forbidden]
[MINYAMI][INFO] Update Token: 31951910.c5w9ls1ny7_q67yzl_1lnmqq3n9tmuz
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 403
[MINYAMI][WARN] Downloading or decrypting 10350066.ts failed. Retry later. [403 Forbidden]
[MINYAMI][INFO] Chunk group action <ping> finished.
[MINYAMI][WARN] Downloading or decrypting 10350066.ts failed. Retry later. [403 Forbidden]
[MINYAMI][INFO] Chunk group action <ping> finished.
[MINYAMI][INFO] Saving task status.
[MINYAMI][INFO] Downloaded: 2070; Waiting for download: 1
[MINYAMI][INFO] Please wait.

E:\>minyami -r "https://pa12480c7cd.dmc.nico/hlsarchive/ht2_nicolive/nicolive-hamster-lv323870210_main_372db4047aa995f97460859880ba0676bb046986b078d40fd3e88bed19c12af8/1/ts/playlist.m3u8?start_time=-574748470294&ht2_nicolive=31951910.8ukqwx1nz0_q67y6u_5nntwvwt1l6o&start=2406.288" --key "lv323870210_31951910_1582655573_d0433cac4a9eeda42b5408cd37ed421b6a0c3751"
[MINYAMI][INFO] Previous task found. Resuming.
[MINYAMI][INFO] Start fetching M3U8 file.
[MINYAMI][INFO] M3U8 file fetched.
[MINYAMI][INFO] Site comfirmed: NicoNico.
[MINYAMI][INFO] Enhanced mode for Nico-TS enabled
[MINYAMI][INFO] Update Token: 31951910.8ukqwx1nz0_q67y6u_5nntwvwt1l6o
[MINYAMI][INFO] Start downloading with 5 thread(s).
[MINYAMI][INFO] Chunk group action <ping> finished.
[MINYAMI][WARN] Downloading or decrypting 10350066.ts failed. Retry later. [403 Forbidden]
[MINYAMI][INFO] Chunk group action <ping> finished.
[MINYAMI][WARN] Downloading or decrypting 10350066.ts failed. Retry later. [403 Forbidden]
[MINYAMI][INFO] Chunk group action <ping> finished.

![retry](https://user-images.githubusercontent.com/61431488/75184407-2c66c700-56f9-11ea-9bed-391db7d335ac.png)

**Comment by Last-Order** [comment]
请问视频时长是多少，这个下不过来的块是视频的最后吗？（每块一般是5秒）

**Comment by gellneko** [comment]
> 请问视频时长是多少，这个下不过来的块是视频的最后吗？（每块一般是5秒）
视频的时长是2:22:31，下不下来的第2071块是视频的最后

**Comment by Last-Order** [comment]
因为并非顺序下载所以2071块未必是视频的最后。理论上`10350066.ts`应该是第10350秒的视频内容，应该也是最后了，你可以试试用`--slice`把最后的一点点排除在外..试试

此外没有账号我很难确定具体问题，如果可以的话可以通过邮件给我一个账号来测试一下（
来信请寄`sora@sound.moe`

**Comment by Last-Order** [comment]
should be fixed by 56a642ef066caa8c3288422263d2908b03ae449f
