### ISSUE TITLE
下载过程无限报403

### ISSUE THREAD

**Issue by Etherrrr** [Last-Order/Minyami#43]
**Basic Information**
* Node.js version: 10.15.2
* Minyami version: 3.0.2
* Minyami Extractor (Chrome Extension) version:1.1.9
* Video URL: https://live2.nicovideo.jp/watch/lv324753714

**Describe the bug**
timeshift非公开的直播，用普雷米进行回看时获取了下载地址，使用minyami进行下载的过程中无限报403
（图片不知道为什么传不上来）

**Comment by Etherrrr** [comment]
经反复尝试后确认属于正常情况……

**Comment by Last-Order** [comment]
非公开也是支持的。请先参考一下https://www.bilibili.com/read/cv3340753这篇文章。
