### ISSUE TITLE
给了--key的值，但还是去拉取了m3u8文件里的key文件

### ISSUE THREAD

**Issue by shetz163** [Last-Order/Minyami#45]
**Basic Information**
* Minyami version: 3.0.8

因为拉取m3u8和key的地址使用了不同的cookie，所以我先尝试着拉取了key文件的值（不确定拉取的方式是否正确，获取到key文件，把它转成了hex）然后将其填入到了--key，但minyami好像还是去拉取m3u8里的key文件，希望可以优先判断是否存在key，或者可以设置不同地址使用不同的cookie（比如像header里面的set-cookie）。
还有一个问题，可以在自己的ts文件里来调用minyami包吗？尝试导入了minyami包，但没有太弄清楚该怎么去调用它。

**Comment by Last-Order** [comment]
1. 可以，我下个版本加一下
2. Minyami目前还是设计为一个CLI应用，没有留出相应接口，不过这个需求确实存在，我可能会在下个版本加上
