### ISSUE TITLE
下载nico直播被403后未保留以往文件

### ISSUE THREAD

**Issue by need123tan** [Last-Order/Minyami#48]
Minyami version: 3.1.3
Minyami Chrome Extension version: 1.1.17
video url: niconico生放送

在扩展中勾选下载直播，抓取直播的平台为ubuntu 18.04 LTS （日本vps），使用扩展的平台为Windows 10。两者IP不一致。

在抓取nico生放送被403后，并未保留之前已抓取的视频。

[MINYAMI][INFO] Start fetching M3U8 file.
[MINYAMI][INFO] M3U8 file fetched.
[MINYAMI][INFO] Start fetching M3U8 file.
[MINYAMI][INFO] M3U8 file fetched.
[MINYAMI][INFO] Proccessing 11499.ts finished. (497 / unknown | Avg Speed: 2.00 chunks/s or 1.00x)
[MINYAMI][INFO] Proccessing 11500.ts finished. (498 / unknown | Avg Speed: 2.01 chunks/s or 1.00x)
[MINYAMI][INFO] Start fetching M3U8 file.
[MINYAMI][INFO] M3U8 file fetched.
[MINYAMI][INFO] Start fetching M3U8 file.
[MINYAMI][INFO] M3U8 file fetched.
[MINYAMI][INFO] Proccessing 11502.ts finished. (499 / unknown | Avg Speed: 2.00 chunks/s or 1.00x)
[MINYAMI][INFO] Proccessing 11501.ts finished. (500 / unknown | Avg Speed: 2.01 chunks/s or 1.00x)
[MINYAMI][INFO] Start fetching M3U8 file.
[MINYAMI][INFO] M3U8 file fetched.
[MINYAMI][INFO] Start fetching M3U8 file.
[MINYAMI][INFO] M3U8 file fetched.
[MINYAMI][INFO] Proccessing 11504.ts finished. (501 / unknown | Avg Speed: 2.00 chunks/s or 1.00x)
[MINYAMI][INFO] Proccessing 11503.ts finished. (502 / unknown | Avg Speed: 2.01 chunks/s or 1.00x)
[MINYAMI][INFO] Start fetching M3U8 file.
[MINYAMI][INFO] M3U8 file fetched.
[MINYAMI][INFO] Start fetching M3U8 file.
[MINYAMI][INFO] M3U8 file fetched.
[MINYAMI][WARN] Downloading or decrypting 11505.ts failed. Retry later. [403 Forbidden]
[MINYAMI][WARN] Processing 11505.ts failed.
[MINYAMI][WARN] Downloading or decrypting 11506.ts failed. Retry later. [403 Forbidden]
[MINYAMI][WARN] Processing 11506.ts failed.
[MINYAMI][WARN] Downloading or decrypting 11506.ts failed. Retry later. [403 Forbidden]
[MINYAMI][WARN] Processing 11506.ts failed.
[MINYAMI][WARN] Downloading or decrypting 11505.ts failed. Retry later. [403 Forbidden]
[MINYAMI][WARN] Processing 11505.ts failed.
[MINYAMI][WARN] Downloading or decrypting 11506.ts failed. Retry later. [403 Forbidden]
[MINYAMI][WARN] Processing 11506.ts failed.
[MINYAMI][WARN] Downloading or decrypting 11505.ts failed. Retry later. [403 Forbidden]
[MINYAMI][WARN] Processing 11505.ts failed.
[MINYAMI][WARN] Downloading or decrypting 11505.ts failed. Retry later. [403 Forbidden]
[MINYAMI][WARN] Processing 11505.ts failed.
[MINYAMI][WARN] Downloading or decrypting 11506.ts failed. Retry later. [403 Forbidden]
[MINYAMI][WARN] Processing 11506.ts failed.
[MINYAMI][INFO] Start fetching M3U8 file.
[MINYAMI][WARN] Downloading or decrypting 11505.ts failed. Retry later. [403 Forbidden]
[MINYAMI][WARN] Processing 11505.ts failed.
[MINYAMI][WARN] Downloading or decrypting 11506.ts failed. Retry later. [403 Forbidden]
[MINYAMI][WARN] Processing 11506.ts failed.
[MINYAMI][WARN] Downloading or decrypting 11507.ts failed. Retry later. [403 Forbidden]
[MINYAMI][WARN] Processing 11507.ts failed.
[MINYAMI][WARN] Fail to fetch M3U8 file: [403 Forbidden]
[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.
[MINYAMI][INFO] Try again.
[MINYAMI][WARN] Downloading or decrypting 11506.ts failed. Retry later. [403 Forbidden]
[MINYAMI][WARN] Processing 11506.ts failed.
[MINYAMI][WARN] Downloading or decrypting 11505.ts failed. Retry later. [403 Forbidden]
[MINYAMI][WARN] Processing 11505.ts failed.
[MINYAMI][WARN] Downloading or decrypting 11505.ts failed. Retry later. [403 Forbidden]
[MINYAMI][WARN] Processing 11505.ts failed.
[MINYAMI][WARN] Downloading or decrypting 11507.ts failed. Retry later. [403 Forbidden]
[MINYAMI][WARN] Processing 11507.ts failed.
[MINYAMI][WARN] Fail to fetch M3U8 file: [403 Forbidden]
[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.
[MINYAMI][INFO] Try again.
[MINYAMI][WARN] Downloading or decrypting 11506.ts failed. Retry later. [403 Forbidden]
[MINYAMI][WARN] Processing 11506.ts failed.
[MINYAMI][WARN] Downloading or decrypting 11505.ts failed. Retry later. [403 Forbidden]
[MINYAMI][WARN] Processing 11505.ts failed.
[MINYAMI][WARN] Downloading or decrypting 11506.ts failed. Retry later. [403 Forbidden]
[MINYAMI][WARN] Processing 11506.ts failed.
[MINYAMI][WARN] Downloading or decrypting 11507.ts failed. Retry later. [403 Forbidden]
[MINYAMI][WARN] Processing 11507.ts failed.
[MINYAMI][WARN] Fail to fetch M3U8 file: [403 Forbidden]
[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.
[MINYAMI][INFO] Try again.
[MINYAMI][WARN] Downloading or decrypting 11505.ts failed. Retry later. [403 Forbidden]
[MINYAMI][WARN] Processing 11505.ts failed.
[MINYAMI][WARN] Downloading or decrypting 11507.ts failed. Retry later. [403 Forbidden]
[MINYAMI][WARN] Processing 11507.ts failed.
[MINYAMI][WARN] Downloading or decrypting 11506.ts failed. Retry later. [403 Forbidden]
[MINYAMI][WARN] Processing 11506.ts failed.
[MINYAMI][WARN] Fail to fetch M3U8 file: [403 Forbidden]
[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.
[MINYAMI][WARN] Max retries exceeded. Abort.
Error: Max retries exceeded.
    at Object.<anonymous> (/usr/lib/node_modules/minyami/dist/utils/m3u8.js:45:31)
    at Generator.throw (<anonymous>)
    at rejected (/usr/lib/node_modules/minyami/dist/utils/m3u8.js:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[MINYAMI][ERROR] Aborted due to critical error.

**Comment by Last-Order** [comment]
保留了，在你的系统临时文件夹里会有（Windows为%TEMP%），需要你手动合并一下。
这不是一个bug，是预期行为。另外其实不建议使用Minyami录制Nico直播~
