### ISSUE TITLE
Site Support Request (Please Post Here)

### ISSUE THREAD

**Issue by Last-Order** [Last-Order/Minyami#5]
Please post sites you want minyami to support here.

**Comment by jzhang046** [comment]
Hi, 

Could you please add support for music videos on [http://www.sonymusic.co.jp/](http://www.sonymusic.co.jp/
)? The videos on this site seems to be provided by [brightcove](https://www.brightcove.com/en/). 

By the way, I have tried to use the `Minyami Extractor` that you have developed on this site and found that the addresses for `m3u8` videos seems to be obfuscated. 

Again, thank you for developing this project! 

Best regards,

**Comment by Last-Order** [comment]
@jzhang046 
Hi,
Could you please provide a url that contains a video on this site? I can only find embedded YouTube videos.

**Comment by jzhang046** [comment]
@Last-Order 
Hi, 

Thank you so much for the reply. 

Please find the videos under this [page](http://www.sonymusic.co.jp/video/category/MV). 

Best regards,

**Comment by Last-Order** [comment]
@jzhang046 
I've supported this site in version 1.1.5. Please update both Minyami and Minyami Extractor to try it.
BTW, I added English UI for Minyami Extractor.

**Comment by Last-Order** [comment]
> [https://gyao.yahoo.co.jp/title/名探偵コナン/5bd6b0cf-779a-4cc7-bf35-40934d3cd39e](https://gyao.yahoo.co.jp/title/%E5%90%8D%E6%8E%A2%E5%81%B5%E3%82%B3%E3%83%8A%E3%83%B3/5bd6b0cf-779a-4cc7-bf35-40934d3cd39e)
> This link is not supported, Please repair it.

Fixed in Minyami Chrome Extension 1.0.9, please update your chrome extension.

**Comment by Last-Order** [comment]
@iotmemo 

The common parser works for this site. Just use: 

`minyami -d <m3u8 file url>`

For example:
`minyami -d https://manifest.prod.boltdns.net/license/v1/aes128/5467539670001/198aec32-3033-4312-b4e5-de9cc8c82180/3362e71c-11a6-4acc-bb2e-b5cba3ca8996?fastly_token=NWM2YTI0MDVfNzM1MTQ2NDBhMDA2NmU5ZGFmYzczNTNmZWVmMGZhNDlmZDgwYTExNjlmYzcyYzU1ODY0ODY2YzI0YTBjMDY2MA%3D%3D`
