### ISSUE TITLE
【Abema TV streaming live 限时回看视频】fail to fetch m3u8 file：

### ISSUE THREAD

**Issue by joyimayday** [Last-Order/Minyami#50]
**Basic Information**
* Node.js version: 12.18.4
* Minyami version: 3.1.7
* Minyami Extractor (Chrome Extension) version:1.1.17
* Video URL: minyami -d "https://vod-abematv.akamaized.net/ppv/slot/EQT5RAs47DiX5y/1080/playlist.m3u8?aver=BetCNSDBQQCNTZ&ccf=11&dt=pc_chrome&enc=clear" --output "TRIPLE AXE ONE MAN SHOW 2020 -15 MANIAX-  【ABEMA】テレビ＆ビデオエンターテインメント.ts" --key "32bb68bf231fd57301135cb42988ac0d" --live --threads 20 --proxy "127.0.0.1:1080"

Abema直播回看视频，有时间限制，目前还在时效内，挂了日本原生IP，一直不成功

C:\Joy>minyami -d "https://vod-abematv.akamaized.net/ppv/slot/EQT5RAs47DiX5y/1080/playlist.m3u8?aver=BetCNSDBQQCNTZ&ccf=11&dt=pc_chrome&enc=clear" --output "TRIPLE AXE ONE MAN SHOW 2020 -15 MANIAX-  【ABEMA】テレビ＆ビデオエンターテインメント.ts" --key "32bb68bf231fd57301135cb42988ac0d" --live --threads 20 --proxy "127.0.0.1:1080"
[MINYAMI][INFO] Start fetching M3U8 file.
[MINYAMI][WARN] Fail to fetch M3U8 file: [UNKNOWN]
[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.
[MINYAMI][INFO] Try again.
[MINYAMI][WARN] Fail to fetch M3U8 file: [UNKNOWN]
[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.
[MINYAMI][INFO] Try again.
[MINYAMI][WARN] Fail to fetch M3U8 file: [UNKNOWN]
[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.
[MINYAMI][INFO] Try again.
[MINYAMI][WARN] Fail to fetch M3U8 file: [UNKNOWN]
[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.
[MINYAMI][WARN] Max retries exceeded. Abort.
Error: Max retries exceeded.
    at Object.<anonymous> (C:\Users\yu\AppData\Roaming\npm\node_modules\minyami\dist\utils\m3u8.js:45:31)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\yu\AppData\Roaming\npm\node_modules\minyami\dist\utils\m3u8.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[MINYAMI][ERROR] Aborted due to critical error.

**Comment by Last-Order** [comment]
先别用--proxy试试 用Proxifier之类的软件挂代理

joyimayday <notifications@github.com> 于2020年9月20日周日 下午2:58写道：
