### ISSUE TITLE
macOS 下无法下载视频

### ISSUE THREAD

**Issue by Caringor** [Last-Order/Minyami#51]
尝试下载视频时提示「Fail to fetch M3U8 file」，已排除代理问题

[MINYAMI][INFO] Start fetching M3U8 file.
[MINYAMI][WARN] Fail to fetch M3U8 file: [UNKNOWN]
[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.
[MINYAMI][INFO] Try again.
[MINYAMI][WARN] Fail to fetch M3U8 file: [UNKNOWN]
[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.
[MINYAMI][INFO] Try again.
[MINYAMI][WARN] Fail to fetch M3U8 file: [UNKNOWN]
[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.
[MINYAMI][INFO] Try again.
[MINYAMI][WARN] Fail to fetch M3U8 file: [UNKNOWN]
[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.
[MINYAMI][INFO] Try again.

**Comment by Last-Order** [comment]
使用的何种代理

**Comment by Caringor** [comment]
HTTP 的，是因为不支持的关系吗？

**Comment by Last-Order** [comment]
--proxy <socks-proxy>     Download via Socks proxy
