### ISSUE TITLE
niconico下载失败

### ISSUE THREAD

**Issue by klj1999** [Last-Order/Minyami#53]
最新版的minyami
[MINYAMI][MERGING] [░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0% 1      throw er; // Unhandled 'error' event
      ^                                                           
Error: ENOENT: no such file or directory, open '【無料】にじさん 'Emitted 'error' event on WriteStream instance at:
    at internal/fs/streams.js:375:14                                  at FSReqCallback.oncomplete (fs.js:164:23) {
  errno: -2,                                                        code: 'ENOENT',
  syscall: 'open',
  path: '【無料】にじさんじ「SMASH The PAINTcd /sdcard/Download  '

链接:https://live2.nicovideo.jp/watch/lv328087060

**Comment by Last-Order** [comment]
看起来是输出文件名的问题，可以--output手动指定一下你这是在什么系统跑的？？

**Comment by klj1999** [comment]
我是安卓 termux跑的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Eridanus Sora"<notifications@github.com&gt;; 
发送时间: 2020年9月22日(星期二) 晚上7:21
收件人: "Last-Order/Minyami"<Minyami@noreply.github.com&gt;; 
抄送: "孔令佳"<908569308@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Last-Order/Minyami] niconico下载失败 (#53)





 
看起来是输出文件名的问题，可以--output手动指定一下
 你这是在什么系统跑的？？

**Comment by Last-Order** [comment]
可能是shell的问题，你先试试手动指定输出文件名。

**Comment by Last-Order** [comment]
因无回应关闭issue，如有更多问题请重开。
