### ISSUE TITLE
无法通过 clash 代理下载

### ISSUE THREAD

**Issue by Yesterday17** [Last-Order/Minyami#60]
**Basic Information**
* Node.js version: v12.18.3
* Minyami version: Minyami / A lovely video downloader / 3.1.11
* Minyami Extractor (Chrome Extension) version: 1.1.21
* Video URL: https://live2.nicovideo.jp/watch/lv328666629

**Describe the bug**
当手动通过 `--proxy`(deprecated) 指定 clash 的代理端口时，持续出现 `[ETIMEOUT]`；当使用 `$ENV.proxy` 时，提示 `[ECONNRESET]`。
```
$Env:http_proxy="http://127.0.0.1:7890";$Env:https_proxy="http://127.0.0.1:7890"
```

**Screenshots**
![image](https://user-images.githubusercontent.com/8667822/98943903-2c2e8600-252b-11eb-8398-d96e6ebe0af6.png)

**Comment by Last-Order** [comment]
![image](https://user-images.githubusercontent.com/3362825/99507175-04716f00-29be-11eb-95e8-436a385dfd83.png)
你地址没加引号？

顺便一提代理是废弃功能，不要用了。HTTP_PROXY环境变量也不吃，请用其他方法。

**Comment by wangebcjd** [comment]
我也出现了相同问题，请问其他方法指什么？

**Comment by Yesterday17** [comment]
~~透 明 代 理~~
