### ISSUE TITLE
abema回放下载失败

### ISSUE THREAD

**Issue by lingless** [Last-Order/Minyami#62]
**Basic Information**
* Node.js version: 11.4.0
* Minyami version: 3.1.7
* Minyami Extractor (Chrome Extension) version:1.1.23
* Video URL: https://abema.tv/video/episode/90-1372_s10_p1002

前天还能正常用，今天一直弹错，什么设置都没改过。
会不会和chrome插件更新有关？插件更新后没有端口设置了，因为我电脑之前不加端口就下载失败，现在也尝试过加端口还是不行。
![image](https://user-images.githubusercontent.com/75372540/100876868-f275ed00-34e2-11eb-9d0e-4dd125ac7f9c.png)

**Comment by Last-Order** [comment]
挂代理，推荐使用Proxifier。
原先的--proxy不推荐使用了，不过你还是可以手动打上，应该是可以用的

**Comment by lingless** [comment]
可以了，原来是我打端口没加空格。换了个旧版的插件不用手打了。谢谢~
