### ISSUE TITLE
Minyami 如何实现 下载Live 一段时间后停止 

### ISSUE THREAD

**Issue by FrankScarlet** [Last-Order/Minyami#73]
## 环境

> 预期的执行环境

- Docker
- Alpine里的Node.js （当前LTS 14.16.1）
- 对应Minyami 4.2.2

## 情况

之前一直用定时任务，结合命令来录制A&G的广播，但感觉访问出错的概率有点高（443），而且yi
`ffmpeg -i https://fms2.uniqueradio.jp/agqr10/aandg1.m3u8 -t 1860 x.mp4`

我想起Minyami应该也能完成类似的事情
`minyami -d https://fms2.uniqueradio.jp/agqr10/aandg1.m3u8 --output test_1m.ts --live`

我原本是定时执行ffmpeg命令+时间参数来停止录制，看了下minyami的`--slice "00:00-30:00` 并不适用。

`--live`这个命令是会一直下载，直到键盘输入Ctrl+C 才停止，我想除非我定时启动一个执行这个命令的程序，然后三十分钟后给这个进程发一个Ctrl+C的信号停止，才能实现原有的类似功能...

我目前只能想到这么多，想问一下minyami有没有支持一段时间后停止录制的方法，或者只能从底层多写一个逻辑才行...

**Comment by x15120** [comment]
minyami的--slice是对archive档靠猜实现的，并不是ffmpeg那样读取文件内容进行编辑的功能，相比之下，使用代码定时30分钟后kill掉下载或use minyami as library都是可行的选择。另外，推荐使用https://www.uniqueradio.jp/agplayerf/hls/HLS_Layer1-cdn.m3u8

**Comment by FrankScarlet** [comment]
> minyami的--slice是对archive档靠猜实现的，并不是ffmpeg那样读取文件内容进行编辑的功能，相比之下，使用代码定时30分钟后kill掉下载或use minyami as library都是可行的选择。另外，推荐使用https://www.uniqueradio.jp/agplayerf/hls/HLS_Layer1-cdn.m3u8

您这个地址的来源是啥啊，我之后换这个试试。我是进官网然后点那个`On Air`，然后弹出来[这个页面](https://www.uniqueradio.jp/agplayer5/player.php)，然后F11看的。

我的问题已经得到了一定的解答，等有进一步的实现方法的时候我会补充在这个Issue里。

**Comment by Last-Order** [comment]
建议您使用外部控制实现此功能
