### ISSUE TITLE
#72 break same of the usage

### ISSUE THREAD

**Issue by climba03003** [Last-Order/Minyami#78]
**Basic Information**
* Node.js version: 16
* Minyami version: 4.2.2
* Minyami Extractor (Chrome Extension) version:
* Video URL: 1.m3u8

**Describe the bug**
#72 break the below usage

Full List of breaking example

Local File Usage
host: `./foo.m3u8`
host: `foo.m3u8`

~~M3U8 File which use file name only
host: `https://test.com/foo.m3u8`
path: `foo.key`~~

**Reason Behind**
`new URL` parser only accept full URL.

**To Reproduce**

**Expected behavior**
Same as before. Captured from version 4.2.1
![image](https://user-images.githubusercontent.com/23028015/122637461-609d9c80-d121-11eb-9e09-44fdd9e7b82e.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/23028015/122637440-3cda5680-d121-11eb-97b3-01fc371f3fc7.png)

**Comment by fireattack** [comment]
I don't understand the second example.
```
M3U8 File which use file name only
host: https://test.com
path: foo.key
```

This won't work before 4.2.2 either. It will just return "https://test.com/foo.key".

**Comment by climba03003** [comment]
> 
> 
> I don't understand the second example.
> 
> ```
> M3U8 File which use file name only
> host: https://test.com
> path: foo.key
> ```
> 
> This won't work before 4.2.2 either. It will just return "https://foo.key
> test2.js:18".

It should works because I have used the file like this before

**Comment by fireattack** [comment]
..which exactly will return `https://foo.key`.

```
Welcome to Node.js v12.20.0.
Type ".help" for more information.
> host = 'https://test.com'
'https://test.com'
> host.match(/(.+\/)/)[1]
'https://'

```

**Comment by climba03003** [comment]
> 
> 
> ..which exactly will return `https://foo.key`.
> 
> ```
> Welcome to Node.js v12.20.0.
> Type ".help" for more information.
> > host = 'https://test.com'; path = 'foo.key';
> 'foo.key'
> > host.match(/(.+\/)/)[1]
> 'https://'
> > host.match(/(.+\/)/)[1] + path
> 'https://foo.key'
> >
> ```

I just simplified too much for the host. Will always contain `something.m3u8` in the end.
host: https://google.com/foo.m3u

**Comment by fireattack** [comment]
OK. This case isn't broken though. >4.2.2 can return the same thing.

```
function buildFullUrl2(host, path) {
    return new URL(path, host).href;
}
console.log(buildFullUrl2("https://google.com/a.m3u8", "foo.key"))

// https://google.com/foo.key
test2.js:23
```

**Comment by climba03003** [comment]
> 
> 
> OK. This case isn't broken though. >4.2.2 can return the same thing.
> 
> ```js
> function buildFullUrl2(host, path) {
>     return new URL(path, host).href;
> }
> console.log(buildFullUrl2("https://google.com/a.m3u8", "foo.key"))
> 
> // https://google.com/foo.key
> ```

![image](https://user-images.githubusercontent.com/23028015/122638085-ab6ce380-d124-11eb-8dd3-842fda42c78e.png)

**Comment by fireattack** [comment]
Because you joined it in wrong order

**Comment by climba03003** [comment]
> 
> 
> Because you joined it in wrong order

I double check it and see the problem. Then only the local path problem exist.
