### ISSUE TITLE
关于retries的建议

### ISSUE THREAD

**Issue by scqy2000** [Last-Order/Minyami#8]
能否加入非直播视频重试的限制次数的自主调整？
最近从ssr换了v2ray，网速快了但是响应慢一些，只有一次重试经常无法正常下载
![0030-08-20 14 11 12](https://user-images.githubusercontent.com/19802266/44323273-b3433f80-a483-11e8-844a-b7d30fc8dddc.png)

**Comment by Last-Order** [comment]
好，今后可以加入自定重试次数的功能。
关于下载非直播视频，目前就重新执行一下命令好了。
