### ISSUE TITLE
[Feature request] add parameter to redirect temporarily path

### ISSUE THREAD

**Issue by lsylsy2** [Last-Order/Minyami#80]
Scenario:
When capturing videos using a server (VPS, Cloud server, etc.), it's usual to have system disk and data disks seperated, and /tmp mouted to the system disk which is not big enough to hold all the segment files.
Adding a parameter allowing to save temp files in specified path can solve this problem.

**Comment by Last-Order** [comment]
You can use environment variables (`TEMP` on Windows or `TMPDIR` on common Linux distributions) to set the directory of temprorary files. 

On Windows:
```cmd
set TEMP=D:/temp/ && minyami ...
```

On Linux
```bash
export TMPDIR=/foo/bar && minyami ...
```

**Comment by Last-Order** [comment]
Docs updated.
