### ISSUE TITLE
Fail to fetch M3U8 file: [403 Forbidden]

### ISSUE THREAD

**Issue by railannad** [Last-Order/Minyami#83]
日本成人直播网站FC2， 根据 #6 ，大佬在2020年5月份就说了支持这个网站，今天试了一下 给我报403了。救救孩子

 `minyami -d https://hls.live.fc2.com/hls/95909233/2/master_playlist?targets=10,20,30,40,50,90&session_token=6e21714fb7d54b063cd1dfa8b241bf5ca0a5ff0dafce9eccdcf4455e128bb8d4&playlist_token=18a37f9cd447e6e9e520a4a808efb33acda81871c1e6bc65fcc496a246ec1efc&playlist_second_token=8abc6c08a130d9b2a769987f98f027a38db0b9cc421d9f3118ede3341b8d6e25`
`[1] 16780`
`[2] 16781`
`[3] 16782`
`root@Cloud:~/Minyami# [MINYAMI][INFO] Start fetching M3U8 file.`
`[MINYAMI][WARN] Fail to fetch M3U8 file: [403 Forbidden]`
`[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.`
`[MINYAMI][INFO] Try again.`
`[MINYAMI][WARN] Fail to fetch M3U8 file: [403 Forbidden]`
`[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.`
`[MINYAMI][INFO] Try again.`
`[MINYAMI][WARN] Fail to fetch M3U8 file: [403 Forbidden]`
`[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.`
`[MINYAMI][INFO] Try again.`
`[MINYAMI][WARN] Fail to fetch M3U8 file: [403 Forbidden]`
`[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.`
`[MINYAMI][INFO] Try again.`
`[MINYAMI][WARN] Fail to fetch M3U8 file: [403 Forbidden]`
`[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.`
`[MINYAMI][INFO] Try again.`
`[MINYAMI][WARN] Fail to fetch M3U8 file: [403 Forbidden]`
`[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.`
`[MINYAMI][WARN] Max retries exceeded. Abort.`
`Error: Error: Request failed with status code 403`
`    at Object.<anonymous> (/usr/local/lib/node_modules/minyami/dist/utils/m3u8.js:67:31)`
 `   at Generator.throw (<anonymous>)`
`    at rejected (/usr/local/lib/node_modules/minyami/dist/utils/m3u8.js:25:65)`
`    at <anonymous>`
`    at process._tickCallback (internal/process/next_tick.js:188:7)`
`[MINYAMI][ERROR] Aborted due to critical error.`

**Comment by tuzi3040** [comment]
地址加引号

**Comment by railannad** [comment]
> 地址加引号

![image](https://user-images.githubusercontent.com/36919867/126931825-fcc1a2bc-a988-40a8-8255-7e31bfbc6013.png)
加完一样403

**Comment by tuzi3040** [comment]
可能地址过期了，ua，cookie，header，ip什么的，这个就不是mnm的问题了

**Comment by railannad** [comment]
> 可能地址过期了，ua，cookie，header，ip什么的，这个就不是mnm的问题了

报错信息变成了 `Fail to fetch M3U8 file: [UNKNOWN]`  

![image](https://user-images.githubusercontent.com/36919867/126934291-4d4df471-b7eb-4246-915f-3c54a6d84f74.png)

**Comment by tuzi3040** [comment]
请根据 help 示例正确填写 proxy 的值

**Comment by railannad** [comment]
> 请根据 help 示例正确填写 proxy 的值

![image](https://user-images.githubusercontent.com/36919867/126935068-4886afb8-5cde-4291-a4e6-5e34d9d42e07.png)
然后控制台无限重复打印`start fetching M3U8 file `-> `M3U8 file fetched.` ，本地也并没有生成文件

**Comment by tuzi3040** [comment]
> 可能地址过期了，ua，cookie，header，ip什么的，这个就不是mnm的问题了

请如此所述自行测试解决

**Comment by railannad** [comment]
> > 可能地址过期了，ua，cookie，header，ip什么的，这个就不是mnm的问题了
> 
> 请如此所述自行测试解决
> 或者去掉 `--live` 试试看

在控制台手动设置代理，然后不使用minyami的代理参数就好了，很神奇。
我找的那个网站是播电视剧的，已经播了240小时了，不太可能失效...

**Comment by Last-Order** [comment]
如果您要提报问题，请提供必要的基本信息。建议使用 Issue Template 提交，谢谢。
