### ISSUE TITLE
Can chunkname be added to the ‘chunk-error’ event arguments

### ISSUE THREAD

**Issue by zyzsdy** [Last-Order/Minyami#92]
When using minyami as library to build an app, the `task.filename` here is very useful, but there is no way to receive it outside.

https://github.com/Last-Order/Minyami/blob/be5410a29d7da7637eadf293390b64e13fcccd3b/src/core/live.ts#L272

https://github.com/Last-Order/Minyami/blob/be5410a29d7da7637eadf293390b64e13fcccd3b/src/core/live.ts#L279

**Comment by Last-Order** [comment]
see 9e0d85946fd58a059fe4d32da78f82a83a5aea81

**Comment by zyzsdy** [comment]
awesome!!!, love you.
