### ISSUE TITLE
Mac system usage problems

### ISSUE THREAD

**Issue by lazyTimes** [Last-Order/Minyami#93]
When using on a mac computer, I found that an error was reported every time the last resource was downloaded

[MINYAMI][INFO] Processing seg-516-v1-a1.m4s finished. (600 / 601 or 99.83% | Avg Speed: 0.32 chunks/s or 1.89x | ETA: 3s)
[MINYAMI][WARN] Downloading or decrypting init-v1-a1.mp4 failed. Retry later. [Cannot read property 'startsWith' of undefined]
[MINYAMI][WARN] Downloading or decrypting init-v1-a1.mp4 failed. Retry later. [Cannot read property 'startsWith' of undefined]
[MINYAMI][WARN] Downloading or decrypting init-v1-a1.mp4 failed. Retry later. [Cannot read property 'startsWith' of undefined]
[MINYAMI][WARN] Downloading or decrypting init-v1-a1.mp4 failed. Retry later. [Cannot read property 'startsWith' of undefined]
[MINYAMI][WARN] Downloading or decrypting init-v1-a1.mp4 failed. Retry later. [Cannot read property 'startsWith' of undefined]
[MINYAMI][WARN] Downloading or decrypting init-v1-a1.mp4 failed. Retry later. [Cannot read property 'startsWith' of undefined]

**Comment by fireattack** [comment]
Example url? By searching "init-v1-a1.mp4" it looks like an advanced m3u8 with `#EXT-X-MAP` which I don't know if minyami can parse properly

**Comment by zyzsdy** [comment]
Try to introduce the scope of the problem, such as which website will cause it. 

By the way, many problems come from your minyami version is too low, please let us know your minyami version when you open the issue.

**Comment by lazyTimes** [comment]
I have downloaded the desired video through IDM last night

**Comment by Last-Order** [comment]
差不多得了.jpg
