### ISSUE TITLE
4.5.0版本录制直播流无法停止

### ISSUE THREAD

**Issue by ashkyrene** [Last-Order/Minyami#96]
**Basic Information**
* Node.js version: 
* Minyami version: 
* Minyami Extractor (Chrome Extension) version:
* Video URL: 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="484" alt="image_2022-02-06_19-59-02" src="https://user-images.githubusercontent.com/51735114/152712655-113c5ea7-93d1-4ae0-9a3f-4379e17af20f.png">

**Comment by Last-Order** [comment]
Should be fixed in 4.5.1. Please have a try.

**Comment by ashkyrene** [comment]
Thank you very much, I will donate to support.

Eridanus Sora ***@***.***> 于2022年2月7日周一 10:53写道：
