### ISSUE TITLE
建议：合并后删除块用outputFileList遍历，然后删且仅删除空目录

### ISSUE THREAD

**Issue by fireattack** [Last-Order/Minyami#97]
今天遇到这么个场景，用minyami下载时livestreaming已经开始很久，于是我用其他方式把前面的块给下了，顺手放在minyami的临时目录里，准备全部下完自己再合并

结果发现minyami下完之后把整个目录给删了

虽然确实是一个比较罕见的场景，但是感觉设计上还是不要去动非程序建立的文件好一点

**Comment by Last-Order** [comment]
30f47d3369525097eb562aed15b1e66afdb5f439

**Comment by fireattack** [comment]
赞美
